### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by sleupold** [weggetor/BBImageStory#3]
in Quick Settings, "Templates", "View Template" and "List Template" are not translated (I checked my language pack, and it is complete).
I also suggest renaming "View Template" to "Detail Template" or "Item Template".

**Comment by weggetor** [comment]
Done

**Comment by sleupold** [comment]
[ResourcePack.BBImageStory_Module.1.0.0.de-DE.zip](https://github.com/weggetor/BBImageStory/files/537525/ResourcePack.BBImageStory_Module.1.0.0.de-DE.zip)
I confirm it to be fixed (see attached version of German LP)
